Add support for hvr/multi-ghc-travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,3 +1,40 @@
-language: haskell
-script: cabal configure --enable-tests --enable-benchmarks && cabal build && cabal test && cabal bench
-install: cabal install --enable-tests --enable-benchmarks
+env:
+ - GHCVER=6.12.3
+ - GHCVER=7.0.1
+ - GHCVER=7.0.2
+ - GHCVER=7.0.3
+ - GHCVER=7.0.4
+ - GHCVER=7.2.1
+ - GHCVER=7.2.2
+ - GHCVER=7.4.1
+ - GHCVER=7.4.2
+ - GHCVER=7.6.1
+ - GHCVER=7.6.2
+ - GHCVER=7.6.3
+ - GHCVER=head
+
+before_install:
+ - sudo add-apt-repository -y ppa:hvr/ghc
+ - sudo apt-get update
+ - sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy
+ - export PATH=/opt/ghc/$GHCVER/bin:$PATH
+
+install:
+ - cabal-1.18 update
+ - cabal-1.18 install --only-dependencies --enable-tests --enable-benchmarks
+
+script:
+ - cabal-1.18 configure --enable-tests --enable-benchmarks -v2
+ - cabal-1.18 build
+ - cabal-1.18 test
+ - cabal-1.18 check
+ - cabal-1.18 sdist
+
+ - export SRC_TGZ=$(cabal-1.18 info . | awk '{print $2 ".tar.gz";exit}') ;
+   cd dist/;
+   if [ -f "$SRC_TGZ" ]; then
+      cabal-1.18 install "$SRC_TGZ";
+   else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+   fi
